# Generated by Django 5.1.5 on 2026-03-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMBPathConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название настройки')),
                ('search_path', models.CharField(help_text='Например: \\\\10.29.107.16\\белоус а.н\\тест скрипта', max_length=500, verbose_name='Путь для поиска файлов ВК')),
                ('result_path', models.CharField(help_text='Например: \\\\10.29.107.16\\белоус а.н\\результат', max_length=500, verbose_name='Путь для сохранения результатов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройка SMB пути',
                'verbose_name_plural': 'Настройки SMB путей',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
