# Generated by Django 5.1.5 on 2026-05-12 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMBFileIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_extension', models.CharField(choices=[('xlsx', 'Excel XLSX'), ('xls', 'Excel XLS'), ('xlsm', 'Excel XLSM')], max_length=10, verbose_name='Тип файла')),
                ('file_path', models.CharField(max_length=1000, verbose_name='Полный путь к файлу')),
                ('relative_path', models.CharField(blank=True, max_length=1000, verbose_name='Относительный путь')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Размер файла (байт)')),
                ('modified_time', models.DateTimeField(blank=True, null=True, verbose_name='Время изменения')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('last_checked', models.DateTimeField(auto_now=True, verbose_name='Последняя проверка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexed_files', to='statement.smbpathconfig', verbose_name='Конфигурация SMB')),
            ],
            options={
                'verbose_name': 'Индекс SMB файла',
                'verbose_name_plural': 'Индексы SMB файлов',
                'indexes': [models.Index(fields=['config', 'is_available', 'filename'], name='statement_s_config__d9a2f9_idx'), models.Index(fields=['config', 'file_extension'], name='statement_s_config__27f60d_idx')],
                'unique_together': {('config', 'file_path')},
            },
        ),
    ]
