# Generated by Django 5.1.5 on 2026-05-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0002_smbfileindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMBIndexSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включить автоматическую индексацию')),
                ('schedule_type', models.CharField(choices=[('disabled', 'Отключено'), ('hourly', 'Каждый час'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('custom', 'Своё расписание')], default='daily', max_length=20, verbose_name='Периодичность')),
                ('custom_hour', models.IntegerField(choices=[(0, '00:00'), (1, '01:00'), (2, '02:00'), (3, '03:00'), (4, '04:00'), (5, '05:00'), (6, '06:00'), (7, '07:00'), (8, '08:00'), (9, '09:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00'), (23, '23:00')], default=2, help_text='Для ежедневного или кастомного расписания', verbose_name='Час (0-23)')),
                ('custom_minute', models.IntegerField(choices=[(0, '00'), (5, '05'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50'), (55, '55')], default=0, help_text='Для точной настройки времени', verbose_name='Минута (0-55 с шагом 5)')),
                ('custom_day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], default=1, help_text='Для еженедельного расписания', verbose_name='День недели')),
                ('custom_day_of_month', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (28, '28'), (29, '29'), (30, '30'), (31, '31')], default=1, help_text='Для ежемесячного расписания (1-31)', verbose_name='День месяца')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Следующий запуск')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Расписание индексации SMB',
                'verbose_name_plural': 'Расписание индексации SMB',
            },
        ),
    ]
