# Generated by Django 5.1.5 on 2026-05-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0003_smbindexschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMBIndexSchedule',
        ),
    ]
