# Generated by Django 5.1.5 on 2026-05-13 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0004_delete_smbindexschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время обработки')),
                ('rows_processed', models.IntegerField(default=0, verbose_name='Обработано строк')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'В обработке'), ('processed', 'Обработан'), ('error', 'Ошибка'), ('skipped', 'Пропущен')], default='processed', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Лог обработанных файлов',
                'verbose_name_plural': 'Логи обработанных файлов',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='smbpathconfig',
            options={'ordering': ['config_type', '-is_active', 'name'], 'verbose_name': 'Настройка SMB пути', 'verbose_name_plural': 'Настройки SMB путей'},
        ),
        migrations.RemoveIndex(
            model_name='smbfileindex',
            name='statement_s_config__d9a2f9_idx',
        ),
        migrations.AddField(
            model_name='smbfileindex',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время обработки'),
        ),
        migrations.AddField(
            model_name='smbfileindex',
            name='processing_error',
            field=models.TextField(blank=True, verbose_name='Ошибка обработки'),
        ),
        migrations.AddField(
            model_name='smbfileindex',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'В обработке'), ('processed', 'Обработан'), ('error', 'Ошибка'), ('skipped', 'Пропущен')], default='pending', max_length=20, verbose_name='Статус обработки'),
        ),
        migrations.AddField(
            model_name='smbpathconfig',
            name='config_type',
            field=models.CharField(choices=[('search', 'Поиск ВК (незаполненные ведомости)'), ('accounting_source', 'Accounting Data Source (готовые ведомости)')], default='search', max_length=20, verbose_name='Тип конфигурации'),
        ),
        migrations.AlterField(
            model_name='smbpathconfig',
            name='result_path',
            field=models.CharField(blank=True, help_text="Для конфигураций типа 'Поиск ВК'", max_length=500, verbose_name='Путь для сохранения результатов (только для поиска ВК)'),
        ),
        migrations.AlterField(
            model_name='smbpathconfig',
            name='search_path',
            field=models.CharField(help_text='Например: \\\\10.29.107.16\\папка', max_length=500, verbose_name='Путь для поиска файлов'),
        ),
        migrations.AddIndex(
            model_name='smbfileindex',
            index=models.Index(fields=['config', 'is_available', 'processing_status'], name='statement_s_config__d2f9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='smbfileindex',
            index=models.Index(fields=['processing_status', 'is_available'], name='statement_s_process_aca181_idx'),
        ),
        migrations.AddField(
            model_name='processedfilelog',
            name='file_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='statement.smbfileindex', verbose_name='Файл'),
        ),
    ]
