# Generated by Django 5.1.5 on 2025-02-10 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Комментарий склада',
                'verbose_name_plural': 'Комментарии склада',
            },
        ),
        migrations.CreateModel(
            name='Leading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Ведущий',
                'verbose_name_plural': 'Ведущие',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Запрос', max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Supler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, verbose_name='Номер счета')),
                ('date', models.DateField(verbose_name='Дата')),
                ('article', models.CharField(max_length=100, verbose_name='Артикул')),
                ('project', models.CharField(blank=True, max_length=100, null=True, verbose_name='Проект')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('unit', models.CharField(default='шт', max_length=50, verbose_name='Единица измерения')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('description_problem', models.TextField(blank=True, null=True, verbose_name='Описание проблемы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comers.comment', verbose_name='Комментарий')),
                ('leading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comers.leading', verbose_name='Руководитель')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comers.specialist', verbose_name='Специалист')),
                ('status', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='comers.status', verbose_name='Статус')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comers.supler', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Позиции в обработке',
                'verbose_name_plural': 'Позиции в обработке',
            },
        ),
    ]
