# Generated by Django 5.1.5 on 2025-12-17 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='party',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='comers.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Статус'),
        ),
    ]
