# Generated by Django 5.1.5 on 2025-07-29 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_requestcounter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestcounter',
            options={'verbose_name': 'Счетчик запросов', 'verbose_name_plural': 'Счетчики запросов'},
        ),
        migrations.AlterModelOptions(
            name='uniqueip',
            options={'verbose_name': 'Уникальный IP', 'verbose_name_plural': 'Уникальные IP'},
        ),
    ]
