# Generated by Django 5.1.5 on 2025-02-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_table',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='article',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='base_unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='index_remains',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='party',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='title',
            field=models.TextField(),
        ),
    ]
