# Generated by Django 5.1.5 on 2025-02-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahr', '0002_alter_data_table_address_alter_data_table_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_table',
            name='index_remains',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
