# Generated by Django 5.1.5 on 2025-07-29 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahr', '0003_alter_data_table_index_remains'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data_table',
            options={'verbose_name_plural': 'С.А.ХР'},
        ),
        migrations.AlterModelOptions(
            name='deleted',
            options={'verbose_name_plural': 'Архив'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'История изменений'},
        ),
        migrations.AlterField(
            model_name='data_table',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='article',
            field=models.CharField(max_length=60, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='base_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Единица'),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='index_remains',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='party',
            field=models.CharField(max_length=20, verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='deleted',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='deleted',
            name='article',
            field=models.TextField(null=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='deleted',
            name='comment',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='deleted',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='deleted',
            name='party',
            field=models.CharField(max_length=9, null=True, verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='deleted',
            name='title',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='history',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='history',
            name='article',
            field=models.TextField(null=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='history',
            name='comment',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='history',
            name='data_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahr.data_table', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата именения'),
        ),
        migrations.AlterField(
            model_name='history',
            name='party',
            field=models.CharField(max_length=9, null=True, verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='history',
            name='title',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
    ]
