# Generated by Django 5.1.5 on 2026-06-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='№ТН, ТТН')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='Дата поступления')),
                ('article', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Код (Артикул)')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Наименование')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Место хранения')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Кол-во')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Инвентарная запись',
                'verbose_name_plural': 'Инвентарные записи',
                'db_table': 'inventory_items',
                'ordering': ['-created_at'],
            },
        ),
    ]
