# Generated by Django 5.1.5 on 2026-06-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_inventoryitem_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='parent',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='components',
            field=models.JSONField(blank=True, default=list, help_text="Список комплектующих: [{'article': '...', 'name': '...', 'quantity': ...}]", verbose_name='Комплектующие'),
        ),
    ]
