# Generated by Django 5.1.5 on 2025-02-19 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=20, verbose_name='')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='')),
            ],
            options={
                'verbose_name': 'Доступ по ссылкам',
                'verbose_name_plural': 'Доступы по ссылкам',
            },
        ),
    ]
