# Generated by Django 5.1.5 on 2025-02-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('gray', 'Gray')], default='gray', max_length=50, verbose_name='Цвет точки (CSS-класс или hex-код)')),
            ],
            options={
                'verbose_name': 'Статус проекта',
                'verbose_name_plural': 'Статусы проектов',
            },
        ),
    ]
