# Generated by Django 5.1.5 on 2025-03-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_linkaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkaccess',
            name='link_name',
            field=models.CharField(choices=[('поиск', 'Поиск'), ('заметки', 'Заметки'), ('сахр', 'Сахр'), ('архив', 'Архив'), ('недопоставки', 'Недопоставки'), ('инвентаризация', 'Инвентаризация'), ('таблица аналогов', 'Таблица аналогов'), ('бтк', 'БТК'), ('отзывы и предложения', 'Отзывы и предложения'), ('обновить базу', 'Обновить базу')], max_length=20, verbose_name='Строка меню'),
        ),
        migrations.AlterField(
            model_name='remains',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
