# Generated by Django 5.1.5 on 2025-05-26 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_alter_linkaccess_link_name_alter_remains_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StandardValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='finder.standard')),
            ],
            options={
                'verbose_name': 'Аналоги',
                'ordering': ['value'],
                'unique_together': {('standard', 'value')},
            },
        ),
    ]
