# Generated by Django 5.1.5 on 2025-06-18 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_standard_standardvalue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardvalue',
            options={'ordering': ['value'], 'verbose_name': 'Аналоги', 'verbose_name_plural': 'Аналоги'},
        ),
        migrations.AlterField(
            model_name='standard',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='standardvalue',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='finder.standard', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='standardvalue',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
