# Generated by Django 5.1.5 on 2025-11-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_alter_standardvalue_options_alter_standard_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_code', models.CharField(max_length=50, verbose_name='Код бухгалтерский')),
                ('nomenclature_kd', models.CharField(max_length=255, verbose_name='Номенклатура КД')),
                ('accounting_name', models.CharField(max_length=500, verbose_name='Наименование бухгалтерское')),
            ],
            options={
                'verbose_name': 'Бухгалтерская запись',
                'verbose_name_plural': 'Бухгалтерские данные',
            },
        ),
    ]
