# Generated by Django 5.1.5 on 2025-12-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0006_accountingdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingdata',
            options={'verbose_name': 'Данные сопоставления ТН\\КД', 'verbose_name_plural': 'Данные сопоставления ТН\\КД'},
        ),
        migrations.AlterModelOptions(
            name='standard',
            options={'verbose_name': 'Стандарт', 'verbose_name_plural': 'Стандарты'},
        ),
        migrations.AlterModelOptions(
            name='standardvalue',
            options={'ordering': ['value']},
        ),
    ]
