# Generated by Django 5.1.5 on 2026-05-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0007_alter_accountingdata_options_alter_standard_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountingdata',
            unique_together={('accounting_code', 'nomenclature_kd')},
        ),
        migrations.AddIndex(
            model_name='accountingdata',
            index=models.Index(fields=['accounting_code', 'nomenclature_kd'], name='finder_acco_account_9225a6_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingdata',
            index=models.Index(fields=['nomenclature_kd'], name='finder_acco_nomencl_f7e133_idx'),
        ),
    ]
