# Generated by Django 5.1.5 on 2026-09-24 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkwearCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('standard_lifespan', models.PositiveIntegerField(default=365, verbose_name='Стандартный срок эксплуатации (дней)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Категория спецодежды',
                'verbose_name_plural': 'Категории спецодежды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Отдел')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('last_name', 'first_name', 'patronymic')},
            },
        ),
        migrations.CreateModel(
            name='WorkwearItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('size', models.CharField(blank=True, max_length=20, verbose_name='Размер')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Цвет')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiration_date', models.DateField(verbose_name='Дата окончания срока эксплуатации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workwear_items', to='workwear.workwearcategory', verbose_name='Категория')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workwear_items', to='workwear.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Предмет спецодежды',
                'verbose_name_plural': 'Предметы спецодежды',
                'ordering': ['employee', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkwearHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('issued', 'Выдана'), ('returned', 'Возвращена'), ('written_off', 'Списана'), ('replaced', 'Заменена'), ('updated', 'Обновлена')], max_length=20, verbose_name='Действие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workwear_history_new', to='workwear.employee', verbose_name='Новый сотрудник')),
                ('previous_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workwear_history_previous', to='workwear.employee', verbose_name='Предыдущий сотрудник')),
                ('workwear_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workwear.workwearitem', verbose_name='Предмет спецодежды')),
            ],
            options={
                'verbose_name': 'История спецодежды',
                'verbose_name_plural': 'История спецодежды',
                'ordering': ['-created_at'],
            },
        ),
    ]
