# Generated by Django 5.1.5 on 2026-07-27 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkwearCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('standard_lifespan', models.PositiveIntegerField(default=365, verbose_name='Стандартный срок эксплуатации (дней)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Категория спецодежды',
                'verbose_name_plural': 'Категории спецодежды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Табельный номер')),
                ('department', models.CharField(max_length=100, verbose_name='Отдел')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('photo', models.URLField(blank=True, null=True, verbose_name='Фото (URL из LDAP)')),
                ('ldap_dn', models.CharField(blank=True, max_length=255, verbose_name='LDAP DN')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkwearItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('serial_number', models.CharField(blank=True, max_length=50, verbose_name='Серийный номер')),
                ('size', models.CharField(blank=True, max_length=20, verbose_name='Размер')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Цвет')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiration_date', models.DateField(verbose_name='Дата окончания срока эксплуатации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workwear_items', to='workwear.workwearcategory', verbose_name='Категория')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workwear_items', to='workwear.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Предмет спецодежды',
                'verbose_name_plural': 'Предметы спецодежды',
                'ordering': ['employee', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkwearHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('issued', 'Выдана'), ('returned', 'Возвращена'), ('written_off', 'Списана'), ('replaced', 'Заменена'), ('updated', 'Обновлена')], max_length=20, verbose_name='Действие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workwear_history_created', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('new_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workwear_history_new', to='workwear.employee', verbose_name='Новый сотрудник')),
                ('previous_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workwear_history_previous', to='workwear.employee', verbose_name='Предыдущий сотрудник')),
                ('workwear_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workwear.workwearitem', verbose_name='Предмет спецодежды')),
            ],
            options={
                'verbose_name': 'История спецодежды',
                'verbose_name_plural': 'История спецодежды',
                'ordering': ['-created_at'],
            },
        ),
    ]
