# Generated by Django 5.1.5 on 2026-10-01 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workwear', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workwearitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workwear_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.CreateModel(
            name='OtherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_other_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_items', to='workwear.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Прочий предмет',
                'verbose_name_plural': 'Прочие предметы',
                'ordering': ['-created_at'],
            },
        ),
    ]
